version: '3.8'

services:
  php:
    build: .
    container_name: php_app_lb3
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "8083:80"

  db:
    image: mysql:5.7
    container_name: mysql_db_lb3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lb_pdo_rent
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_lb3
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8084:80"

volumes:
  mysql_data:

